#!/usr/bin/expect -f 

set timeout 3
set default_user "<username>"
set default_host "@<hostname>"

######################################################################

set user $default_user
set password ""
set ssh_args {}

for { set i 0 } { $i<$argc } { incr i } {
  if { [lindex $argv $i] == "-U"
       || [lindex $argv $i] == "--user" } {
    incr i
    set user [lindex $argv $i]
  } elseif { [lindex $argv $i] == "-P"
       || [lindex $argv $i] == "--password" } {
    incr i
    set password [lindex $argv $i]
  } else {
    lappend ssh_args [lindex $argv $i]
  }
}

spawn ssh {*}$ssh_args $user$default_host

if { $password != "" && $user != $default_user } {
  expect "password:" {
    puts "\nwarn: not recomended to enter the password as an argument"
    send "$password\n"
    interact
  }
}

interact
